### ISSUE TITLE
Google Fonts URI protocol in CSS

### ISSUE THREAD

**Issue by robjens** [michelson/Dante#113]
Can we change https://github.com/michelson/Dante/blob/34911ffb30733af0d452f0214dae633554f287fe/dist/css/dante-editor.css#L2 so that it uses `https` over plain http? This current (bower) distribution throws the usual warnings when your site runs under https (while the other way around, it won't) and since a lot of sites use or should use anyway https as default, I think it makes sense to expose the most secure URL to the public.

Cheers

**Comment by michelson** [comment]
yeah. Maybe it could be changed with a `//` in order to work with both protocols.

thanks for report this

**Comment by michelson** [comment]
Oh , wait, 
that is fixed in master branch, but the latest build is missing.
to generate a build to get the latest changes from the source you will have to exec the following in terminal

`bundle install`
`bundle exec middleman build`

you will have to install the development environment first. install ruby , bundler 

sorry for the inconvenience, I will try to release the proper distribution soon. 
I will keep open this until the update.

best

**Comment by michelson** [comment]
updated in master , released in 0.0.15 version

thanks!
