### ISSUE TITLE
Make images linkable

### ISSUE THREAD

**Issue by galki** [michelson/Dante#120]
This is just an idea to one-up the medium.com editor.

We can append a caption to images, so why not also a url.
If the url is input the image gets wrapped in an _a_ tag.

**Comment by michelson** [comment]
Hi , at first view I don't see much sense to implement this on the core of Dante.
primarily because this moves us away from the original Medium model
and because we already have an url tool to make links and image tool.
But you can always can extend Dante to your own purposes. If you need help with that let me know

best
