### ISSUE TITLE
Inline tooltip width with extra_tooltip_widgets

### ISSUE THREAD

**Issue by galki** [michelson/Dante#125]
The code `.inlineTooltip {
   width: auto;
}` and `.inlineTooltip.is-scaled {
    width: auto; }` will fix:

- extra tooltip widgets displaying on new line
- a buglike effect when hiding tooltip menu

**Comment by cristianferrarig** [comment]
Hi @galki, thanks!

This happens when I remove `.is-scaled` class to `.inlineTooltip`:
<img width="611" alt="captura de pantalla 2016-06-15 a las 11 09 41" src="https://cloud.githubusercontent.com/assets/627694/16082960/ab61deba-32e9-11e6-8a36-330716ece243.png">
so that does not happen `.inline Tooltip-menu` need a fixed size.
I solved it through javascript (PR #130) to avoid manual settings, if you have another way to do this, you can send a PR ;)

Thanks again :)

**Comment by galki** [comment]
Nice, thanks!

**Comment by galki** [comment]
I just noticed that if you add any extra_tooltip_widgets the extra items will not be on the same line.

**Comment by cristianferrarig** [comment]
Are you sure you tested on the branch `inline-tooltip-fix`? It works for me.
<img width="638" alt="captura de pantalla 2016-06-16 a las 9 25 47" src="https://cloud.githubusercontent.com/assets/627694/16116659/8fe457f6-33a4-11e6-8e47-d1c865b51461.png">

**Comment by galki** [comment]
I'm sorry, my bad!

**Comment by cristianferrarig** [comment]
No problem! I appreciate it! 👍
