### ISSUE TITLE
How is the content refreshed after save?

### ISSUE THREAD

**Issue by iashris** [michelson/Dante#163]
Noob question here : 

After my content gets saved, how do I re-render my content? I am trying to get this done by making a handler function (store_success_url) that re-renders the html. Is that the right approach?

**Comment by michelson** [comment]
Why do you need to re-render ? the content should be rendered automatically
when typing. maybe a missunderstand something , which html re you trying to
update ?

El 13 dic. 2017 7:53 p. m., "Ashris Choudhury" <notifications@github.com>
escribió:

Noob question here :

After my content gets saved, how do I re-render my content? I am trying to
get this done by making a handler function (store_success_url) that
re-renders the html. Is that the right approach?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/michelson/Dante/issues/163>, or mute the thread

**Comment by iashris** [comment]
Sorry my bad, got it now.
