### ISSUE TITLE
embedding without tempering 

### ISSUE THREAD

**Issue by PedroEsperanca** [michelson/Dante#21]
Currently direct embedding is not possible.
By adding video links it is kinda has the same effect, but by "add an embed" it gets reformatted.

This makes it so that whenever something 'unexpected' gets posted it get's striped of the desired functionality.

**Comment by michelson** [comment]
Hi @PedroEsperanca , this will not be implemented because the main idea of tempering the result of the link is precisely control the presentation. 
What is the `unexpected` use case that are you trying handle ?

**Comment by PedroEsperanca** [comment]
I was thinking about preserving the familiar look of twitter embeds mostly, but would also be helpful for:
8track and spotify playlists
amazon products (also products from any other source)
..anything users find in the all expanding internet

I thought it was wierd that an icon <> was used for a link embed, I think that the link embed should have somehting like : http://fortawesome.github.io/Font-Awesome/icon/link/ or simply: 'http'. And that there should be an optional (to the developer) unfiltered embed (or with custom filtering even).

This project is amazing btw, I might use it in my next project, I'll share it when I do ;)

**Comment by michelson** [comment]
I see, but allowing any html code to be copied would involve unexpected results in the interface, and honestly I think it is complicated to implement because of that.
Dante uses by default Embed.ly to process the Page links and Embeds links, which delivers embed output and other metadata. But you could implement your own server side solution based on oEmbed standards. 

By the way, the button to include embeds is the |> , the <> link is for page links , try some spotify links like http://open.spotify.com/track/3y6r1Pge91vABkxi23iQ8Y , it will display the player when pasted from |> button , and will show the page info when pasted from <> button.

regards

**Comment by PedroEsperanca** [comment]
Thanks for your time good sir, I like your solution.

Some of these concepts are new to me so I had to do some research.

With oembed there really is no need for allowing html.

regards

**Comment by michelson** [comment]
Hi @PedroEsperanca , yeah that´s the whole point about restrict the user input for embeds. OEmbed rocks!
I'm going to close this issue now , but feel free to open new issues if you find problems with Dante

Best!
