### ISSUE TITLE
some embeds don't work yet

### ISSUE THREAD

**Issue by esperancaJS** [michelson/Dante#29]
Almost all of medium/embed.ly supported embeds are working!
List here: https://medium.com/@Medium/embed-videos-tweets-music-and-more-into-your-medium-stories-3b5c09c116e8

But twitter is still not working.
Github and kickstarter also don't work, but Twitter is way more important.

**Comment by michelson** [comment]
Thanks for reporting this @PedroEsperanca , I'll fix this as soon as possible

**Comment by michelson** [comment]
Hi @PedroEsperanca ,
 
Currently twitter & github works as a link embed, not video embed.
But I've done some research today and I found that embedly provides a way to display embeds as `cards`. That will display the content as `medium` does. Although Implement this will imply an addition of dependences. 
I will meditate on this feature and will see which is the best way to integrate or not in the library's core.

Best!

**Comment by PedroEsperanca** [comment]
Oh I see! Didn't know it needed extra dependencies.

As for me I don't mind the dependencies since it even can help with aditional features.
http://blog.embed.ly/post/64786380588/embedly-on-medium-a-better-blogging-experience
These cards seems to help with resizing :)

<hr>

Another thing I noticed that medium does: It only uses the 'default' embed as a last resort, any time you post a link, be it by direct copy paste, by video or embed option it will always look for embedable content provided by the link, only if it doesn't find anything will it post the 'default' embed.
