### ISSUE TITLE
Refactor Dante from Ruby/Rails

### ISSUE THREAD

**Issue by thangngoc89** [michelson/Dante#50]
I didn't code Ruby so I don't understand why are Ruby files there? Is it for build process?

**Comment by michelson** [comment]
yes, the library uses https://middlemanapp.com for development and distribution build.
also Dante is a ruby gem so for ruby / rails projects you can use it as a gem.

**Comment by thangngoc89** [comment]
@michelson I see. But I suggest to seperate the ruby part into a repository. I'll work on a fork for this

**Comment by michelson** [comment]
@thangngoc89 there is no need to do that imo.

Because the ruby part is our development environment. also is used as a ruby gem for Rails/Ruby asset pipeline usage. 

Since only the static assets are included into the bower package (no ruby files) I don't see the inconvenient of use ruby on development.

Is very probable that we are not going to merge PR that rips off our development environment , sorry.

**Comment by thangngoc89** [comment]
@michelson Ok. It's just a little hard for me to set up a development environment.

**Comment by michelson** [comment]
Hi @thangngoc89 , yeah I know that at first install ruby could be more tricky than PHP, but at the end is pure joy :)

if you need help in the process please don't hesitate to ask for help

best!
