### ISSUE TITLE
Feature request: Remove all style for pasted content

### ISSUE THREAD

**Issue by julianfox** [michelson/Dante#56]
Hello,
It would be great to have option for remove all style (e.g: color, text-align, font...) when users paste text.

**Comment by michelson** [comment]
Hi @julianfox , that is already working. maybe you found a bug.
can you show to us the pasted html that gives you trouble?

**Comment by michelson** [comment]
try to paste this html , http://codepen.io/anon/pen/RNqaaQ . I've copy & pasted and is working as spected

**Comment by julianfox** [comment]
Yes with html that work, but when i try to paste text directly from blog article, i paste the style also...

**Comment by michelson** [comment]
Hi @julianfox,  can you point that blog article to test it out? 
best!

**Comment by julianfox** [comment]
Hey @michelson, for exemple with this one: http://www.leblogdebetty.com or this one http://www.helloitsvalentine.fr/0326596/roudoudou

I also try on your app exemple

**Comment by julianfox** [comment]
Hello michelson,
I have this issue on Safari Version 8.0 (10600.1.25.1)
I tried on Chrome without this issue...

**Comment by michelson** [comment]
working now in 0.0.14

**Comment by nceruchalu** [comment]
Hello @michelson,
I still seem to be able to paste pre-formatted text from the codepen snippet you linked to, http://codepen.io/anon/pen/RNqaaQ 

I copied and pasted and got the styles persisted in Safari. Which means I was seeing blue, red and green text in Safari as it was on codepen. BTW I am on a recent version of Safari as required :smile:; Version 8.0.7 (10600.7.12)

When trying this in Chrome the paste worked but also throws in the style such that it now appears as text. Is this the expected behavior? Here's what I got in chrome:
```
p.p1 {margin: 0.0px 0.0px 0.0px 0.0px; font: 32.0px Times; color: #0433ff; -webkit-text-stroke: #0433ff} p.p2 {margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Times; color: #ff2500; -webkit-text-stroke: #ff2500} p.p3 {margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Times; color: #018000; -webkit-text-stroke: #018000} span.s1 {font-kerning: none} 

This is a heading.

This is a paragraph.

This is a paragraph.
```

**Comment by michelson** [comment]
Hi @julianfox , I've tested the pasted content in safari 8.0.5 and chrome 44.02 but I have not been able to reproduce the bug. It works as spected. in http://michelson.github.io/Dante/ version 0.0.14
are you trying it with latest version  0.0.14 ?

**Comment by nceruchalu** [comment]
Hello @julianfox I repeated this using your test website  http://michelson.github.io/Dante/ which I believe is version 0.0.14

I've noticed that pasting works perfectly on Windows. However I'm noticing this issue on a Mac OSX. Are you by any chance using a windows machine?

**Comment by nceruchalu** [comment]
Hello @michelson repeated this using your test website http://michelson.github.io/Dante/ which I believe is version 0.0.14

I've noticed that pasting works perfectly on Windows. However I'm noticing this issue on a Mac OSX. Are you by any chance using a windows machine?

**Comment by michelson** [comment]
nope , I'm using OSX

**Comment by nceruchalu** [comment]
Okay that's odd. I too am on OSX. Here's a screenshot of what I see.

![Awesome Editor, sad paste](http://imgur.com/lDnxJkE.png)

Maybe there's something funny going on with my Mac OS (version 10.10.4). But I also notice that the keyboard commands such as `<command>+B` don't work on bolding text, and same goes for `<command>+I`. Does this extra info help in diagnosing the issue?

This issue aside, this is an awesome library! Thanks for the great work!

**Comment by michelson** [comment]
Ah , I've reproduced this but with pasting content from right click -> context menu -> paste. 
but it works as spected with cmd + v.
Are you using cmd + v or context menu -> paste ?

thanks

**Comment by nceruchalu** [comment]
Actually was using cmd + v. Just tried context menu -> paste and got the same results.

It's possible that safari on my laptop has some weird configs that you only see with the context menu. I say this because cmd + I keeps trying to email the contents of the entire page using the default mail.app. Weird because this doesn't happen in other WYSIWYG editors. But it's pretty cool functionality if it's by design :smile:

**Comment by michelson** [comment]
thank for reporting this @nceruchalu , I will reopen this issue now
