### ISSUE TITLE
Angular Directive

### ISSUE THREAD

**Issue by justmyfreak** [michelson/Dante#71]
Hi, 

I really fall in love with this medium-like editor. However, I didn't find AngularJS Directive for this editor.
Is there any intention to create AngularJS version of this editor?

Thanks

**Comment by michelson** [comment]
I don't know why an Angular directive is needed in order to make Dante work in Angular applications. 
if that's true, you will need an Angular directive for any JS plugin out there ? uhm, that sounds really crappy.
The core team behind Dante have are no intentions to create an AngularJs version for this, but I think it will just work without much hassle if you init the Editor in a Angular controller ???. I really don't use Angular so I don't know much.

but @julianfox was working on an Angular directive, maybe he can share the experience of it and create a Wiki page ?

**Comment by julianfox** [comment]
Hey, yes i did an Angular directive for Dante, i have to found time for clean it and create a repo, but no problem @justmyfreak for share about it ;-)

**Comment by michelson** [comment]
:+1: cool @julianfox !

**Comment by justmyfreak** [comment]
cool @julianfox ! Looking forward to it. In case you need help, I can help too :)

**Comment by justmyfreak** [comment]
@julianfox is there any update? :)

**Comment by julianfox** [comment]
Hey @justmyfreak i will try to publish the directive today, we use it actually for development, but it's far form perfect, it'll a good opportunity to improve it together ;-)

**Comment by julianfox** [comment]
I'll keep you in the loop

**Comment by julianfox** [comment]
Hey @justmyfreak i just created a repo for the directive https://github.com/julianfox/angular-dante :-)

**Comment by julianfox** [comment]
I'll improve the doc soon, the most important is that i don't use the store mechanism of Dante and i reproduce it directly in the directive for use ng-model... may be that can be improved ?

It is a first release, so may be there are some bugs and things to improve, pull requests are welcome ;-)

**Comment by justmyfreak** [comment]
Thanks @julianfox. 

Sure, I'll send pull request if I find something can be improved or fixed :D
