### ISSUE TITLE
Pre-formatted HTML

### ISSUE THREAD

**Issue by jbolles5** [michelson/Dante#90]
Is there anyway to skip the sanitize step for Dante when pre-loading the body? I am using Dante in conjunction with a change tracking editor: https://github.com/NYTimes/ice

It works great with authoring the content and saving, but when loading pre-existing content into the editor, all of the track change styles are removed by Dante. It would be really nice to be able to programmatically skip that step.

Thanks!

**Comment by michelson** [comment]
Hi @jbolles5 ,

I will not recommend that because is possible to break some things into the editor, right now the only way is to hack the base code to allow some styles , whitelisting some attrs in the sanitize step.
what kind of styles are added by the `ice` plugin ?

FYI, for pre existing code in my apps I ended using a server side procesor to clean the posts before displaying it in the browser.

best!

**Comment by jbolles5** [comment]
Thanks for the quick response. It just throws a span tag around the text with a few styles and some data for a tool tip:

```
<span title="Deleted by Justin Bolles - 07/30/2015 11:40am" data-time="1438270851336" data-username="Justin Bolles" data-userid="6" data-cid="177" class="del cts-1">changed text</span>
```

**Comment by michelson** [comment]
Ok , actually we are whitelisting some kind of span , look at https://github.com/michelson/Dante/blob/master/app/assets/javascripts/dante/editor.js.coffee#L1027-L1031
maybe you could add some other checks to it to allow span with class `del` && `add` , you have to try it an see how it works, is possible that some editor features breaks in some point (like delete content or arrow navigation??)

tell me how it goes

best!

**Comment by jbolles5** [comment]
Thanks! That works perfectly. I will keep an eye out of unexpected issues.
